import React from 'react';
import { CustomerOrder, OrderStatus } from '../adminTypes';
import { Check, ChevronRight, X } from 'lucide-react';

interface Props { orders: CustomerOrder[]; onStatus: (id: string, status: OrderStatus) => void; onReject: (id: string, reason: string) => void; }
const progression: OrderStatus[] = ['Accepted', 'Preparing', 'Ready for Pickup', 'Out for Delivery', 'Delivered'];
export const AdminOrderManager: React.FC<Props> = ({ orders, onStatus, onReject }) => <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>{orders.length === 0 && <div style={empty}>No customer orders yet.</div>}{orders.slice().reverse().map(order => <article key={order.id} style={orderCard}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 14, flexWrap: 'wrap' }}><div><span style={eyebrow}>{order.id} · {new Date(order.createdAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</span><h3 style={name}>Rs. {order.total.toLocaleString()}</h3><p style={muted}>{order.items.map(item => `${item.quantity}× ${item.item.name}`).join(' · ')}</p>{(order.contactNumber || order.address) && <p style={customerDetails}>{order.contactNumber && <>Phone: {order.contactNumber}</>}{order.contactNumber && order.address && ' · '}{order.address && <>Address: {order.address}</>}</p>}</div><span style={{ ...pill, background: order.status === 'Rejected' ? '#F6DCD5' : order.status === 'Pending' ? '#F8E7B6' : '#DDEBDC', color: order.status === 'Rejected' ? '#963E2E' : '#3D5D40' }}>{order.status}</span></div>{order.status !== 'Rejected' && <><div style={steps}>{progression.map((step, index) => <React.Fragment key={step}><button onClick={() => onStatus(order.id, step)} style={{ ...stepButton, color: progression.indexOf(order.status) >= index ? '#9B612D' : '#A99784' }}><span style={{ ...dot, background: progression.indexOf(order.status) >= index ? '#B67538' : '#E4D7C7' }}>{progression.indexOf(order.status) >= index && <Check size={10} />}</span>{step}</button>{index < progression.length - 1 && <ChevronRight size={13} color="#C8B5A0" />}</React.Fragment>)}</div><div style={actions}>{order.status === 'Pending' && <button onClick={() => onStatus(order.id, 'Accepted')} style={{ ...action, background: '#47704E', color: 'white' }}>ACCEPT ORDER</button>}{order.status !== 'Pending' && order.status !== 'Delivered' && <button onClick={() => onStatus(order.id, 'Pending')} style={{ ...action, background: '#F2DFA9', color: '#5E471C' }}>SET PENDING</button>}<button onClick={() => onReject(order.id, window.prompt('Reason for rejection?', 'Out of ingredients') || 'Rejected by staff')} style={{ ...action, background: '#F6DCD5', color: '#963E2E' }}><X size={13} /> REJECT</button></div></>}</article>)}</div>;
const orderCard: React.CSSProperties = { background: '#FFF9F2', border: '1px solid #E4D7C7', borderRadius: 16, padding: 18 };
const empty: React.CSSProperties = { background: '#FFF9F2', padding: 40, textAlign: 'center', color: '#765A43', border: '1px solid #E4D7C7', borderRadius: 16 };
const eyebrow: React.CSSProperties = { color: '#B67538', fontSize: 10, fontWeight: 800, letterSpacing: '.12em' };
const name: React.CSSProperties = { fontFamily: "'Playfair Display',serif", fontSize: 25, margin: '8px 0 4px' };
const muted: React.CSSProperties = { color: '#765A43', fontSize: 12, margin: 0 };
const customerDetails: React.CSSProperties = { color: '#4D392A', fontSize: 12, lineHeight: 1.5, margin: '7px 0 0', whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' };
const pill: React.CSSProperties = { height: 'fit-content', borderRadius: 99, padding: '7px 11px', fontSize: 10, fontWeight: 800 };
const steps: React.CSSProperties = { display: 'flex', alignItems: 'center', gap: 4, overflowX: 'auto', margin: '22px 0 16px', paddingBottom: 3 };
const stepButton: React.CSSProperties = { display: 'flex', alignItems: 'center', gap: 5, flexShrink: 0, border: 0, background: 'transparent', padding: 0, fontSize: 10, fontWeight: 700, cursor: 'pointer' };
const dot: React.CSSProperties = { display: 'grid', placeItems: 'center', width: 19, height: 19, borderRadius: '50%', color: 'white' };
const actions: React.CSSProperties = { display: 'flex', gap: 8, flexWrap: 'wrap' };
const action: React.CSSProperties = { border: 0, borderRadius: 8, padding: '9px 11px', fontSize: 10, fontWeight: 800, letterSpacing: '.04em', display: 'inline-flex', alignItems: 'center', gap: 5, cursor: 'pointer' };
